### PR TITLE
Add c6g restricted and unrestriced nodes to Jenkins

### PR DESCRIPTION
**Pull request by mseth10**
- Add c6g restricted and unrestricted nodes
- Remove p3 restricted and unrestricted nodes
- Add g4 restricted node
- Remove ccache efs

### CODE REVIEW

**Comment by mseth10** [comment]
@josephevans please review, thanks!

**Comment by marcoabreu** [comment]
Where is the ccache config coming from in this setup?

**Comment by mseth10** [comment]
> Where is the ccache config coming from in this setup?

We have too many environment variables in the autoscaling lambda function currently, and there is a limit on the number of characters for environment variables string https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-deployment.html
because of which it doesnt let us add more instances. Hence, cleaning up the environment variables that are no longer in use.

**Comment by marcoabreu** [comment]
Why is it no longer in use? Have you stopped ccache?

**Comment by mseth10** [comment]
> Why is it no longer in use? Have you stopped ccache?

I have not stopped it. But I checked the File Systems in mxnet-ci prod account and both of them havent been used in the last 6 months.

**Review by josephevans — APPROVED** [review]

**Pull request merged**
