### PR TITLE
Replace all test images with images from public domain.

### PR DESCRIPTION
**Pull request by josephevans**
Update LICENSE file to indicate all images in test-data/images are from public domain.

### CODE REVIEW

**Review by leezu — COMMENTED** [review]
Can you include the licensing info somewhere?

**Comment by josephevans** [comment]
> Can you include the licensing info somewhere?

Thanks for the suggestions @leezu, added the licenses of the images that have one.

**Comment by leezu** [comment]
Thank you @josephevans. I'm not sure if we can use images without license, as we may first need to seek permission from the author to redistribute them here as part of Apache. WDYT?

**Comment by josephevans** [comment]
When this is merged, the onnx tests will start failing. I will open a PR with updated URLs as soon as this is merged.

**Review by Zha0q1 — APPROVED** [review]
lgtm

**Comment by marcoabreu** [comment]
Why did we not first fix the tests

**Pull request merged**
