### PR TITLE
add monitor for python docker pipeline

### PR DESCRIPTION
**Pull request by mseth10**
Adding python/docker to be tracked as part of CD pipeline monitor

### CODE REVIEW

**Comment by mseth10** [comment]
@ChaiBapchya how can I test this change using the lambda function?

**Comment by ChaiBapchya** [comment]
https://github.com/apache/incubator-mxnet-ci/blob/7baf37894d853f2c9f53c677b317734586432d00/services/jenkins-pipeline-monitor/deploy_lambda.sh
Run this shell script will deploy the lambda function. I would then go to AWS lambda console & trigger the function to verify the output is as expected.

Other way would be to run handler.py as is locally [not 100% sure if you would hit some issues while doing that]

**Comment by mseth10** [comment]
> https://github.com/apache/incubator-mxnet-ci/blob/7baf37894d853f2c9f53c677b317734586432d00/services/jenkins-pipeline-monitor/deploy_lambda.sh
> Run this shell script will deploy the lambda function.

Thanks @ChaiBapchya . I tried running this script from an ec2 instance in mxnet-ci Isengard account, but ran into some docker issues. Can you also help with the right setup to run this script?

**Comment by waytrue17** [comment]
LGTM, thanks!

**Pull request merged**
